### PR TITLE
Fix config migration

### PR DESCRIPTION
**Pull request by chrwei**
Also leaves original config in place.

### CODE REVIEW

**Comment by caoyue** [comment]
Merged.

**Comment by rpodric** [comment]
Just a further thought on this, which I was reminded of with the most current release. On Windows at least, now that the json is stored in the profile, might it be better to just have it in the root of the WindowsResizer profile folder there rather than in a subfolder according to the version?

Because what happens is that when you install a new version, a new subfolder in the profile is created (0.4.23 in the most recent case) which gets a new json, leaving your real one in whatever the previous folder was (0.4.16 or whatever) for you to copy over manually.

If you do want to maintain separate folders for safety (though many would accumulate over time, but they're tiny, so that's not really relevant) then migrating the json each time would be good, though that might get tricky if the new subfolder doesn't exist yet because the program hasn't been run since updating.

**Comment by caoyue** [comment]
> Just a further thought on this, which I was reminded of with the most current release. On Windows at least, now that the json is stored in the profile, might it be better to just have it in the root of the WindowsResizer profile folder there rather than in a subfolder according to the version?
> 
> Because what happens is that when you install a new version, a new subfolder in the profile is created (0.4.23 in the most recent case) which gets a new json, leaving your real one in whatever the previous folder was (0.4.16 or whatever) for you to copy over manually.
> 
> If you do want to maintain separate folders for safety (though many would accumulate over time, but they're tiny, so that's not really relevant) then migrating the json each time would be good, though that might get tricky if the new subfolder doesn't exist yet because the program hasn't been run since updating.

Also think that's a problem😂, will fix it soon.
Additionally, a portable option maybe helpful?

**Comment by chrwei** [comment]
should be as simple as adding a path.combine("..")?  I haven't tried that though.

I could see an option to store the config in a user specified folder being useful, but that option would need to be stored somewhere else

**Pull request merged**
