### PR TITLE
Add title matching, expand dialog to edit everything

### PR DESCRIPTION
**Pull request by chrwei**
This adds the ability to do simple matches on the title as well as the exe file name, and adds a grid to edit these match strings and the positions.  Config is also moved to a static class so the Settings screen updates can be done in real time.

It also moves the config file to AppData so config can be user specific while still having a single copy of the program.  Also added import/export buttons to easily get at the file for portability and backups. This will allow for a setup program as well since config file permissions won't be an issue anymore.

Few other minor changes for consistency and readability.

### CODE REVIEW

**Comment by caoyue** [comment]
Merged.
Thanks for your great pull request!
And sorry for the late reply, currently not have much time on this project 😂

**Comment by chrwei** [comment]
no problem, I'm just glad to not have to start from scratch.

**Comment by rpodric** [comment]
>It also moves the config file to AppData so config

On this, is it normal that the configuration held in the json for the previous version be lost in the process? Mine was (did it twice to be sure), though fortunately I had a backup so was able to go back to the previous version easily enough.

**Comment by chrwei** [comment]
it moves the file, it's not lost, it's just migrated to a new location

**Comment by rpodric** [comment]
Yes, that wasn't clear. What I meant is that the move happens but it doesn't retain key information to enable it to work.

Positions, yes, but the rest are null::
https://i.imgur.com/HVG0O8G.png

**Comment by chrwei** [comment]
oof, I see where I went wrong, I'll have a fix in a bit, I'll preserve the old file too.

**Comment by rpodric** [comment]
Thanks. BTW, I tried an import just to see if it would fill in the other columns, but it didn't, which probably makes sense since I'm assuming it's the same mechanism as used in the one that occurs upon upgrade.

**Comment by chrwei** [comment]
The Title column wasn't in the original, so that just has to be typed in if
you want to add it.  it'll still match on the exe name alone if title is
blank.

**Comment by caoyue** [comment]
A small update  to compatible with previous version.  #10

**Pull request merged**
